module.exports = {
  content: [
    "./**/*.php",
    "./**/*.js",
    "!./node_modules/**",
    "!./assets/css/**",
  ],
  css: ["./assets/css/fanfiction-frontend.css"],
  output: "./assets/css/purged",
  defaultExtractor: (content) =>
    content.match(/[\w-/:]+(?<!:)/g) || [],
  fontFace: true,
  keyframes: true,
  variables: true,
  safelist: {
    standard: [
      /^fanfic-/,
      /^fanfiction-/,
      /^story-/,
      /^wp-/,
      /^admin-/,
      /^dashicons/,
      /^screen-reader/,
      /^align/,
      /^current/,
      /^logged-in/,
      /^menu-/,
      /^page-/,
      /^post-/,
      /^comment-/,
      /^is-/,
      /^has-/,
      /^open$/,
      /^active$/,
      /^selected$/,
      /^visible$/,
      /^hidden$/,
      /^loading$/,
      /^expanded$/,
      /^collapsed$/,
      /^disabled$/,
      /^error$/,
      /^success$/,
      /^warning$/,
      /^info$/,
      /^fanfic-status-/,
      /^fanfic-story-status-/,
      /^fanfic-age-badge-/,
      /^fanfic-warning-age-/,
      /^story-warning-age-badge/,
      /^fanfic-notification-/,
      /^fanfic-pill-/,
      /^multi-select/,
      /^select2/,
    ],
    deep: [/^(wp|admin|fanfic|fanfiction|story|dashicons)-/],
    greedy: [
      /^(is|has)-/,
      /(open|active|current|selected|hidden|visible|loading|disabled)/,
    ],
  },
};
